export interface Abbreviation {
  word: string;
  abbreviation: string;
}

// Common Air Force abbreviations that vary by AFSC
// Users can customize these based on their career field
export const DEFAULT_ABBREVIATIONS: Abbreviation[] = [
  { word: "maintenance", abbreviation: "maint" },
  { word: "equipment", abbreviation: "equip" },
  { word: "operational", abbreviation: "ops" },
  { word: "operations", abbreviation: "ops" },
  { word: "administration", abbreviation: "admin" },
  { word: "administrative", abbreviation: "admin" },
  { word: "communications", abbreviation: "comm" },
  { word: "communication", abbreviation: "comm" },
  { word: "information", abbreviation: "info" },
  { word: "management", abbreviation: "mgmt" },
  { word: "requirements", abbreviation: "reqs" },
  { word: "requirement", abbreviation: "req" },
  { word: "training", abbreviation: "trng" },
  { word: "personnel", abbreviation: "pers" },
  { word: "organization", abbreviation: "org" },
  { word: "organizational", abbreviation: "org" },
  { word: "development", abbreviation: "dev" },
  { word: "evaluation", abbreviation: "eval" },
  { word: "squadron", abbreviation: "sq" },
  { word: "headquarters", abbreviation: "HQ" },
  { word: "commander", abbreviation: "CC" },
  { word: "superintendent", abbreviation: "supt" },
  { word: "supervisor", abbreviation: "supv" },
  { word: "technical", abbreviation: "tech" },
  { word: "intelligence", abbreviation: "intel" },
  { word: "reconnaissance", abbreviation: "recce" },
  { word: "surveillance", abbreviation: "surv" },
  { word: "aircraft", abbreviation: "acft" },
  { word: "mission", abbreviation: "msn" },
  { word: "configuration", abbreviation: "config" },
  { word: "documentation", abbreviation: "docs" },
  { word: "specification", abbreviation: "spec" },
  { word: "specifications", abbreviation: "specs" },
  { word: "authorization", abbreviation: "auth" },
  { word: "certification", abbreviation: "cert" },
  { word: "qualification", abbreviation: "qual" },
  { word: "qualifications", abbreviation: "quals" },
  { word: "professional", abbreviation: "prof" },
  { word: "government", abbreviation: "govt" },
  { word: "department", abbreviation: "dept" },
  { word: "approximately", abbreviation: "approx" },
  { word: "headquarters", abbreviation: "HQ" },
  { word: "installation", abbreviation: "instl" },
  { word: "environment", abbreviation: "env" },
  { word: "instruction", abbreviation: "instr" },
  { word: "instructions", abbreviation: "instrs" },
  { word: "regulation", abbreviation: "reg" },
  { word: "regulations", abbreviation: "regs" },
  { word: "inspection", abbreviation: "insp" },
  { word: "compliance", abbreviation: "cmpl" },
  { word: "performance", abbreviation: "perf" },
  { word: "assessment", abbreviation: "asmnt" },
  { word: "program", abbreviation: "prgm" },
  { word: "programs", abbreviation: "prgms" },
  { word: "executive", abbreviation: "exec" },
  { word: "management", abbreviation: "mgmt" },
  { word: "coordinated", abbreviation: "coord" },
  { word: "coordinate", abbreviation: "coord" },
  { word: "coordination", abbreviation: "coord" },
  { word: "responsibility", abbreviation: "resp" },
  { word: "responsibilities", abbreviation: "resps" },
  { word: "accomplishment", abbreviation: "accomp" },
  { word: "accomplishments", abbreviation: "accomps" },
  { word: "volunteer", abbreviation: "vol" },
  { word: "volunteers", abbreviation: "vols" },
  { word: "volunteered", abbreviation: "vol'd" },
  { word: "members", abbreviation: "mbrs" },
  { word: "member", abbreviation: "mbr" },
  { word: "hours", abbreviation: "hrs" },
  { word: "minutes", abbreviation: "mins" },
  { word: "dollars", abbreviation: "$" },
  { word: "million", abbreviation: "M" },
  { word: "thousand", abbreviation: "K" },
  { word: "percentage", abbreviation: "%" },
  { word: "percent", abbreviation: "%" },
];

export function formatAbbreviationsList(abbreviations: Abbreviation[]): string {
  return abbreviations
    .map((a) => `"${a.word}" → "${a.abbreviation}"`)
    .join("\n");
}

